import pandas as pd
from sentence_transformers import InputExample

train_data = [
    # Đồ ăn nhanh
    # Đồ ăn nhanh (Fast Food)
    InputExample(texts=['Gà rán KFC', 'Gà rán KFC thập cẩm'], label=1.0),
    InputExample(texts=['Gà rán KFC', 'Gà rán siêu giòn'], label=0.95),
    InputExample(texts=['Gà rán KFC', 'Gà rán siêu cay'], label=0.9),
    InputExample(texts=['Trà sữa TocoToco', 'Trà sữa TocoToco topping trân châu'], label=1.0),
    InputExample(texts=['Trà sữa trân châu', 'Trà sữa Gongcha'], label=0.9),
    InputExample(texts=['Mì Hảo Hảo', 'Mì Hảo Hảo gói'], label=1.0),
    InputExample(texts=['Bánh mì gà', 'Bánh mì kẹp thịt'], label=0.8),
    InputExample(texts=['Khoai tây chiên', 'Khoai tây chiên McDonald\'s'], label=0.9),
    InputExample(texts=['Nước mía', 'Nước mía nguyên chất'], label=1.0),
    InputExample(texts=['Pizza phô mai', 'Pizza Pepperoni'], label=0.9),
    InputExample(texts=['Bánh xèo', 'Bánh xèo miền Tây'], label=0.8),
    InputExample(texts=['Bánh mì kẹp thịt', 'Bánh mì'], label=0.7),
    InputExample(texts=['Súp lươn', 'Cháo lươn'], label=0.9),
    InputExample(texts=['Trà đào Phúc Long', 'Trà đào'], label=1.0),
    InputExample(texts=['Trà xanh C2', 'Trà xanh'], label=1.0),
    InputExample(texts=['Thực phẩm hữu cơ tươi', 'Rau hữu cơ'], label=1.0),
    InputExample(texts=['Cháo gà bổ dưỡng', 'Cháo gà'], label=0.8),
    InputExample(texts=['Trái cây tươi ngon', 'Nho Mỹ nhập khẩu'], label=1.0),
    InputExample(texts=['Cà rốt Đà Lạt', 'Cà rốt'], label=1.0),

    # Bánh mì (Bread)
    InputExample(texts=['Bánh mì thịt', 'Bánh mì kẹp thịt'], label=1.0),
    InputExample(texts=['Bánh mì kẹp thịt', 'Bánh mì kẹp gà'], label=0.8),
    InputExample(texts=['Bánh mì', 'Bánh mì gà'], label=0.7),
    InputExample(texts=['Bánh mì', 'Bánh mì thịt nguội'], label=0.8),
    InputExample(texts=['Bánh mì', 'Bánh mì nướng'], label=0.75),
    InputExample(texts=['Bánh mì kẹp gà', 'Bánh mì gà nướng'], label=0.9),
    InputExample(texts=['Bánh mì kẹp thịt', 'Bánh mì kẹp xúc xích'], label=0.8),
    InputExample(texts=['Bánh mì gà nướng', 'Bánh mì gà quay'], label=0.7),
    InputExample(texts=['Bánh mì đặc biệt', 'Bánh mì thịt đặc biệt'], label=0.9),
    InputExample(texts=['Bánh mì', 'Bánh mì chay'], label=0.6),
    InputExample(texts=['Bánh mì kẹp thịt', 'Bánh mì đặc biệt'], label=0.8),
    InputExample(texts=['Bánh mì kẹp thịt', 'Bánh mì gà nướng'], label=0.7),
    InputExample(texts=['Bánh mì kẹp thịt', 'Bánh mì kẹp trứng'], label=0.6),
    InputExample(texts=['Bánh mì nóng', 'Bánh mì kẹp thịt nguội'], label=0.8),
    InputExample(texts=['Bánh mì gà', 'Bánh mì gà nướng'], label=0.9),
    InputExample(texts=['Bánh mì phô mai', 'Bánh mì thịt'], label=0.7),
    InputExample(texts=['Bánh mì cuốn', 'Bánh mì cuốn thịt'], label=0.8),
    InputExample(texts=['Bánh mì kẹp thịt', 'Bánh mì nướng phô mai'], label=0.9),

    # Đồ chiên (Fried Food)
    InputExample(texts=['Khoai tây chiên', 'Khoai tây chiên giòn'], label=0.95),
    InputExample(texts=['Khoai tây chiên', 'Khoai tây chiên giòn McDonalds'], label=0.9),
    InputExample(texts=['Gà rán', 'Gà chiên giòn'], label=0.85),
    InputExample(texts=['Gà chiên', 'Gà chiên xù'], label=0.8),
    InputExample(texts=['Chả giò', 'Chả giò chiên'], label=0.9),
    InputExample(texts=['Gà chiên', 'Gà nướng'], label=0.7),
    InputExample(texts=['Cánh gà chiên', 'Cánh gà chiên giòn'], label=0.9),
    InputExample(texts=['Chả giò', 'Chả giò chiên giòn'], label=1.0),
    InputExample(texts=['Chả giò', 'Chả giò rán'], label=0.9),
    InputExample(texts=['Mực chiên', 'Mực chiên giòn'], label=0.8),
    InputExample(texts=['Tôm chiên', 'Tôm chiên giòn'], label=1.0),
    InputExample(texts=['Gà rán', 'Gà rán siêu giòn'], label=0.95),
    InputExample(texts=['Chả giò', 'Chả giò chay'], label=0.8),
    InputExample(texts=['Mực chiên giòn', 'Mực chiên giòn Nhật Bản'], label=1.0),
    InputExample(texts=['Gà chiên xù', 'Gà rán'], label=0.9),
    InputExample(texts=['Bánh bao chiên', 'Bánh bao nhân thịt'], label=0.8),
    InputExample(texts=['Bánh bao', 'Bánh bao chiên'], label=0.9),
    InputExample(texts=['Khoai tây chiên', 'Khoai tây chiên phô mai'], label=0.7),

    # Xôi (Sticky Rice)
    InputExample(texts=['Xôi gà', 'Xôi gà nướng'], label=1.0),
    InputExample(texts=['Xôi xéo', 'Xôi đậu xanh'], label=0.9),
    InputExample(texts=['Xôi mặn', 'Xôi mặn thịt'], label=0.8),
    InputExample(texts=['Xôi chiên', 'Xôi chiên giòn'], label=0.85),
    InputExample(texts=['Xôi đậu', 'Xôi đậu xanh'], label=0.7),
    InputExample(texts=['Xôi hạt sen', 'Xôi sen'], label=0.9),
    InputExample(texts=['Xôi nếp', 'Xôi nếp thịt'], label=0.85),
    InputExample(texts=['Xôi xéo', 'Xôi xéo miền Tây'], label=1.0),
    InputExample(texts=['Xôi ngọt', 'Xôi đậu xanh ngọt'], label=0.8),
    InputExample(texts=['Xôi mặn', 'Xôi mặn thịt băm'], label=0.9),
    InputExample(texts=['Xôi lạc', 'Xôi đậu phộng'], label=0.8),
    InputExample(texts=['Xôi gà', 'Xôi gà nướng'], label=0.9),
    InputExample(texts=['Xôi chiên giòn', 'Xôi chiên nhân thịt'], label=0.7),
    InputExample(texts=['Xôi bắp', 'Xôi bắp thịt'], label=0.85),
    InputExample(texts=['Xôi xôi', 'Xôi xôi đậu'], label=0.9),
    InputExample(texts=['Xôi chay', 'Xôi xôi chay'], label=0.8),

    # Đồ nướng (Grilled Food)
    InputExample(texts=['Thịt nướng BBQ', 'Thịt nướng Mỹ'], label=1.0),
    InputExample(texts=['Thịt nướng', 'Thịt nướng vỉa hè'], label=0.85),
    InputExample(texts=['Thịt nướng', 'Gà nướng mật ong'], label=0.9),
    InputExample(texts=['Thịt nướng', 'Bò nướng'], label=0.8),
    InputExample(texts=['Cá nướng', 'Cá nướng muối'], label=0.9),
    InputExample(texts=['Gà nướng', 'Gà nướng vỉa hè'], label=0.8),
    InputExample(texts=['Thịt heo nướng', 'Sườn nướng'], label=0.9),
    InputExample(texts=['Cá nướng', 'Cá hồi nướng'], label=1.0),
    InputExample(texts=['Thịt nướng', 'Thịt nướng kiểu BBQ'], label=0.9),
    InputExample(texts=['Bò nướng', 'Bò nướng kiểu BBQ'], label=0.85),
    InputExample(texts=['Gà nướng', 'Gà nướng sốt mật ong'], label=0.9),
    InputExample(texts=['Cá hồi nướng', 'Cá hồi nướng xốt'], label=1.0),
    InputExample(texts=['Sườn nướng', 'Sườn nướng BBQ'], label=0.8),
    InputExample(texts=['Cá nướng', 'Cá nướng mặn'], label=0.85),
    InputExample(texts=['Gà nướng', 'Gà nướng kiểu Hàn Quốc'], label=0.9),
    InputExample(texts=['Thịt nướng', 'Thịt nướng BBQ Mỹ'], label=1.0),
    InputExample(texts=['Cá nướng', 'Cá hồi nướng kiểu Nhật'], label=1.0),
    InputExample(texts=['Thịt nướng', 'Thịt nướng cuộn'], label=0.7),
    InputExample(texts=['Cơm chiên', 'Cơm chiên dương châu'], label=1.0),
    InputExample(texts=['Cơm chiên', 'Cơm chiên trứng'], label=0.9),
    InputExample(texts=['Cơm tấm', 'Cơm tấm Sài Gòn'], label=1.0),
    InputExample(texts=['Cơm rang', 'Cơm rang thập cẩm'], label=0.9),
    InputExample(texts=['Cơm trắng', 'Cơm nắm'], label=0.7),
    InputExample(texts=['Cơm chiên trứng', 'Cơm chiên'], label=1.0),
    InputExample(texts=['Cơm cuộn', 'Cơm cuộn sushi'], label=0.8),
    InputExample(texts=['Cơm xôi', 'Cơm xôi thịt'], label=0.9),
    InputExample(texts=['Cơm thịt bò', 'Cơm thịt bò xào'], label=1.0),
    InputExample(texts=['Cơm đậu', 'Cơm đậu xanh'], label=0.8),
    InputExample(texts=['Cơm nắm', 'Cơm nắm xôi'], label=0.7),
    InputExample(texts=['Cơm cuộn sushi', 'Cơm cuộn Hàn Quốc'], label=0.9),
    InputExample(texts=['Cơm bento', 'Cơm bento Nhật Bản'], label=1.0),
    InputExample(texts=['Cơm cuộn', 'Cơm cuộn thập cẩm'], label=0.8),
    InputExample(texts=['Cơm hải sản', 'Cơm hải sản nướng'], label=0.9),
    InputExample(texts=['Cơm nắm', 'Cơm nắm thịt'], label=0.8),
    InputExample(texts=['Cơm cuộn chay', 'Cơm cuộn rau'], label=0.7),
    InputExample(texts=['Cơm bento', 'Cơm bento hải sản'], label=1.0),
    InputExample(texts=['Cơm thịt gà', 'Cơm thịt gà xào'], label=0.9),

    # Giải khát (Drinks)
    InputExample(texts=['Trà đào', 'Trà đào Phúc Long'], label=1.0),
    InputExample(texts=['Trà sữa', 'Trà sữa TocoToco'], label=1.0),
    InputExample(texts=['Nước cam tươi', 'Nước ép cam'], label=0.9),
    InputExample(texts=['Nước ép trái cây', 'Nước ép táo'], label=0.8),
    InputExample(texts=['Nước mía', 'Nước mía nguyên chất'], label=1.0),
    InputExample(texts=['Sữa tươi', 'Sữa tươi nguyên chất'], label=0.9),
    InputExample(texts=['Cà phê sữa đá', 'Cà phê'], label=0.8),
    InputExample(texts=['Sữa đặc Ông Thọ', 'Sữa đặc'], label=1.0),
    InputExample(texts=['Trà xanh', 'Trà xanh C2'], label=1.0),
    InputExample(texts=['Cà phê', 'Cà phê đen'], label=0.7),
    InputExample(texts=['Sữa chua', 'Sữa chua Vinamilk'], label=0.9),
    InputExample(texts=['Cà phê sữa', 'Cà phê sữa đá'], label=0.8),
    InputExample(texts=['Nước ép cam', 'Nước ép trái cây'], label=0.8),
    InputExample(texts=['Trà sữa trân châu', 'Trà sữa Gongcha'], label=0.9),
    InputExample(texts=['Nước suối', 'Nước lọc'], label=0.7),
    InputExample(texts=['Trà chanh', 'Trà chanh đường'], label=0.9),
    InputExample(texts=['Trà xanh', 'Trà đào'], label=0.8),
    InputExample(texts=['Nước mía', 'Nước mía tươi'], label=0.9),

    # Hải sản (Seafood)
    InputExample(texts=['Tôm sú', 'Tôm sú tươi'], label=1.0),
    InputExample(texts=['Tôm hùm', 'Tôm hùm Alaska tươi'], label=1.0),
    InputExample(texts=['Cua biển', 'Cua biển tươi'], label=1.0),
    InputExample(texts=['Cá hồi', 'Cá hồi tươi'], label=1.0),
    InputExample(texts=['Cá ngừ', 'Cá ngừ tươi'], label=1.0),
    InputExample(texts=['Mực ống', 'Mực tươi'], label=1.0),
    InputExample(texts=['Cá chẽm', 'Cá chẽm tươi'], label=1.0),
    InputExample(texts=['Cá trích', 'Cá trích tươi'], label=0.9),
    InputExample(texts=['Tôm sú', 'Tôm sú tươi sống'], label=1.0),
    InputExample(texts=['Cua hoàng đế', 'Cua hoàng đế tươi'], label=1.0),
    InputExample(texts=['Cá mackerel', 'Cá hồi tươi'], label=0.85),
    InputExample(texts=['Mực ống', 'Mực ống tươi'], label=1.0),
    InputExample(texts=['Tôm hùm', 'Tôm hùm tươi sống'], label=1.0),
    InputExample(texts=['Cá hồi', 'Cá hồi tươi nhập khẩu'], label=1.0),
    InputExample(texts=['Cua biển', 'Cua biển sống'], label=1.0),
    InputExample(texts=['Cá ngừ', 'Cá ngừ đại dương tươi'], label=1.0),
    InputExample(texts=['Cá lóc', 'Cá lóc tươi'], label=0.9),
    InputExample(texts=['Cá hồng', 'Cá hồng tươi'], label=1.0),
    InputExample(texts=['Mực', 'Mực tươi sống'], label=1.0),
    InputExample(texts=['Cá bớp', 'Cá bớp tươi'], label=0.9),
    InputExample(texts=['Tôm ngón tay', 'Tôm ngón tay tươi'], label=1.0),
    InputExample(texts=['Cua hoàng đế', 'Cua hoàng đế sống'], label=1.0),
    InputExample(texts=['Cá vược', 'Cá vược tươi'], label=0.9),
    InputExample(texts=['Tôm tươi', 'Tôm sú tươi sống'], label=1.0),
    InputExample(texts=['Cá thu', 'Cá thu tươi'], label=1.0),
    InputExample(texts=['Cá kèo', 'Cá kèo tươi'], label=1.0),
    InputExample(texts=['Cá mú', 'Cá mú tươi'], label=0.9),
    InputExample(texts=['Cua biển', 'Cua biển sống nguyên con'], label=1.0),
    InputExample(texts=['Cá sặc', 'Cá sặc tươi'], label=0.9),
    InputExample(texts=['Mực nang', 'Mực nang tươi'], label=1.0),
    InputExample(texts=['Tôm hùm Alaska', 'Tôm hùm tươi sống nhập khẩu'], label=1.0),
    InputExample(texts=['Cá lăng', 'Cá lăng tươi'], label=0.9),
    InputExample(texts=['Cá phi lê', 'Cá phi lê tươi'], label=1.0),
    InputExample(texts=['Tôm bạc', 'Tôm bạc tươi'], label=0.8),
    InputExample(texts=['Cua Cà Mau', 'Cua Cà Mau tươi'], label=1.0),
    InputExample(texts=['Tôm thẻ', 'Tôm thẻ chân trắng tươi'], label=1.0),
    InputExample(texts=['Cá trích', 'Cá trích tươi sống'], label=0.9),
    InputExample(texts=['Cá mồi', 'Cá mồi tươi'], label=0.8),
    InputExample(texts=['Mực ống', 'Mực ống tươi sống'], label=1.0),
    InputExample(texts=['Cá ngừ đại dương', 'Cá ngừ tươi'], label=0.9),
    InputExample(texts=['Tôm rảo', 'Tôm rảo tươi'], label=1.0),
    InputExample(texts=['Cua Cà Mau', 'Cua Cà Mau sống'], label=1.0),
    InputExample(texts=['Cá mú', 'Cá mú tươi sống'], label=0.9),
    InputExample(texts=['Cá hồng', 'Cá hồng sống'], label=1.0),
    InputExample(texts=['Mực nang', 'Mực nang tươi sống'], label=1.0),
    InputExample(texts=['Cá trê', 'Cá trê tươi'], label=0.8),
    InputExample(texts=['Cá hồi', 'Cá hồi tươi tự nhiên'], label=1.0),
    InputExample(texts=['Cua hoàng đế', 'Cua hoàng đế tươi sống'], label=1.0),
    InputExample(texts=['Mực', 'Mực ống sống'], label=0.9),
    InputExample(texts=['Tôm hùm', 'Tôm hùm nguyên con tươi'], label=1.0),
    InputExample(texts=['Cá mú', 'Cá mú tươi sống tại cửa hàng'], label=0.9),
    InputExample(texts=['Tôm sú', 'Tôm sú tươi tự nhiên'], label=1.0),
    InputExample(texts=['Tôm sú', 'Tôm sú đông lạnh'], label=0.6),
    InputExample(texts=['Cua biển', 'Cua biển đông lạnh'], label=0.7),
    InputExample(texts=['Cá hồi', 'Cá hồi phi lê'], label=0.6),
    InputExample(texts=['Cá ngừ', 'Cá ngừ đông lạnh'], label=0.7),
    InputExample(texts=['Mực ống', 'Mực tươi đông lạnh'], label=0.6),
    InputExample(texts=['Cá chẽm', 'Cá chẽm đông lạnh'], label=0.7),
    InputExample(texts=['Cá trích', 'Cá trích đông lạnh'], label=0.6),
    InputExample(texts=['Tôm sú', 'Tôm sú vỏ cứng'], label=0.6),
    InputExample(texts=['Cua hoàng đế', 'Cua hoàng đế đông lạnh'], label=0.7),
    InputExample(texts=['Mực nang', 'Mực tươi đông lạnh'], label=0.6),
    InputExample(texts=['Cá mackerel', 'Cá mackerel đông lạnh'], label=0.7),
    InputExample(texts=['Cá ngừ', 'Cá ngừ tươi nhập khẩu'], label=0.6),
    InputExample(texts=['Mực ống', 'Mực ống khô'], label=0.6),
    InputExample(texts=['Cua biển', 'Cua biển chế biến'], label=0.7),
    InputExample(texts=['Tôm hùm', 'Tôm hùm đông lạnh'], label=0.6),
    InputExample(texts=['Cá hồi', 'Cá hồi phi lê đông lạnh'], label=0.7),
    InputExample(texts=['Cá vược', 'Cá vược tươi'], label=0.6),
    InputExample(texts=['Tôm sú', 'Tôm sú tươi đóng gói'], label=0.6),
    InputExample(texts=['Cua hoàng đế', 'Cua hoàng đế sống'], label=0.7),
    InputExample(texts=['Cá lóc', 'Cá lóc tươi sống'], label=0.6),
    InputExample(texts=['Cá ngừ', 'Cá ngừ tươi sống'], label=0.7),
    InputExample(texts=['Mực', 'Mực nang khô'], label=0.6),
    InputExample(texts=['Cá hồi', 'Cá hồi phi lê đóng gói'], label=0.7),
    InputExample(texts=['Cua biển', 'Cua biển sống nguyên con'], label=0.6),
    InputExample(texts=['Cá sạc', 'Cá sạc tươi'], label=0.7),
    InputExample(texts=['Cua biển', 'Cua biển sống'], label=0.6),
    InputExample(texts=['Tôm thẻ', 'Tôm thẻ chân trắng đông lạnh'], label=0.6),
    InputExample(texts=['Mực', 'Mực ống tươi đóng gói'], label=0.7),
    InputExample(texts=['Cá hồi', 'Cá hồi chế biến sẵn'], label=0.6),
    InputExample(texts=['Tôm rảo', 'Tôm rảo đông lạnh'], label=0.7),
    InputExample(texts=['Tôm hùm Alaska', 'Tôm hùm Alaska đông lạnh'], label=0.7),
    InputExample(texts=['Cá hồi', 'Cá hồi đông lạnh'], label=0.6),
    InputExample(texts=['Tôm sú', 'Tôm sú tươi sống'], label=0.7),
    InputExample(texts=['Cá lăng', 'Cá lăng tươi'], label=0.6),
    InputExample(texts=['Cá phi lê', 'Cá phi lê đông lạnh'], label=0.7),
    InputExample(texts=['Cua hoàng đế', 'Cua hoàng đế sống đông lạnh'], label=0.7),
    InputExample(texts=['Cá lóc', 'Cá lóc chế biến'], label=0.6),
    InputExample(texts=['Mực nang', 'Mực nang tươi sống'], label=0.7),
    InputExample(texts=['Cá ngừ', 'Cá ngừ tươi đặc biệt'], label=0.6),
    InputExample(texts=['Cua Cà Mau', 'Cua biển tươi'], label=0.7),
    InputExample(texts=['Cá phi lê', 'Cá phi lê tươi'], label=0.6),
    InputExample(texts=['Cua Cà Mau', 'Cua Cà Mau tươi sống'], label=0.7),
    InputExample(texts=['Cá vược', 'Cá vược chế biến'], label=0.6),
    InputExample(texts=['Cá trích', 'Cá trích tươi đặc biệt'], label=0.7),
    InputExample(texts=['Tôm ngón tay', 'Tôm ngón tay đông lạnh'], label=0.6),
    InputExample(texts=['Mực ống', 'Mực ống đóng gói'], label=0.7),
    InputExample(texts=['Cua hoàng đế', 'Cua hoàng đế đặc biệt'], label=0.7),
    InputExample(texts=['Cá mực', 'Mực khô'], label=0.6),
    InputExample(texts=['Tôm rảo', 'Tôm rảo đông lạnh tươi'], label=0.7),
    InputExample(texts=['Cua biển', 'Cua biển đặc biệt'], label=0.6),
    # Rau củ (Vegetables)
    InputExample(texts=['Cà chua', 'Cà chua chín'], label=1.0),
    InputExample(texts=['Cà rốt', 'Cà rốt tươi'], label=1.0),
    InputExample(texts=['Dưa leo', 'Dưa leo tươi'], label=1.0),
    InputExample(texts=['Khoai tây', 'Khoai tây tươi'], label=0.9),
    InputExample(texts=['Bí đỏ', 'Bí đỏ Đà Lạt'], label=0.8),
    InputExample(texts=['Cải xanh', 'Cải bó xôi'], label=0.9),
    InputExample(texts=['Bắp cải', 'Bắp cải tươi'], label=0.8),
    InputExample(texts=['Khoai môn', 'Khoai môn tươi'], label=0.7),
    InputExample(texts=['Mướp', 'Mướp tươi'], label=1.0),
    InputExample(texts=['Rau ngót', 'Rau ngót tươi'], label=1.0),
    InputExample(texts=['Rau muống', 'Rau muống tươi'], label=0.9),
    InputExample(texts=['Nấm', 'Nấm mỡ'], label=0.9),
    InputExample(texts=['Củ cải', 'Củ cải tươi'], label=0.8),
    InputExample(texts=['Cà tím', 'Cà tím tươi'], label=0.9),
    InputExample(texts=['Củ hành', 'Củ hành tươi'], label=1.0),
    InputExample(texts=['Ớt', 'Ớt tươi'], label=0.9),
    InputExample(texts=['Gừng', 'Gừng tươi'], label=0.8),

    # Trái cây (Fruits)
    InputExample(texts=['Trái cây tươi', 'Trái cây nhập khẩu'], label=1.0),
    InputExample(texts=['Nho', 'Nho Mỹ'], label=0.9),
    InputExample(texts=['Táo', 'Táo Mỹ'], label=0.8),
    InputExample(texts=['Chuối', 'Chuối tươi'], label=1.0),
    InputExample(texts=['Dưa hấu', 'Dưa hấu tươi'], label=1.0),
    InputExample(texts=['Măng cụt', 'Măng cụt tươi'], label=1.0),
    InputExample(texts=['Dứa', 'Dứa tươi'], label=0.9),
    InputExample(texts=['Cam', 'Cam tươi'], label=0.9),
    InputExample(texts=['Quýt', 'Quýt tươi'], label=0.9),
    InputExample(texts=['Xoài', 'Xoài tươi'], label=1.0),
    InputExample(texts=['Bưởi', 'Bưởi tươi'], label=1.0),
    InputExample(texts=['Mít', 'Mít tươi'], label=0.8),
    InputExample(texts=['Ổi', 'Ổi tươi'], label=0.9),
    InputExample(texts=['Lê', 'Lê tươi'], label=0.8),
    InputExample(texts=['Lựu', 'Lựu tươi'], label=1.0),
    InputExample(texts=['Dâu tây', 'Dâu tây tươi'], label=1.0),
    # 1. THỰC PHẨM TƯƠI SỐNG (50 cặp)
    InputExample(texts=['Cá diêu hồng tươi', 'Cá diêu hồng sống'], label=0.95),
    InputExample(texts=['Tôm sú tươi', 'Tôm sú đông lạnh'], label=0.7),
    InputExample(texts=['Thịt bò Úc', 'Thịt bò nhập khẩu'], label=0.9),
    InputExample(texts=['Rau muống tươi', 'Rau muống hữu cơ'], label=0.85),
    InputExample(texts=['Ức gà tươi', 'Ức gà đóng gói'], label=0.6),
    InputExample(texts=['Cà chua Đà Lạt', 'Cà chua tươi'], label=0.9),
    InputExample(texts=['Mực ống tươi', 'Mực ướp lạnh'], label=0.75),
    InputExample(texts=['Trứng gà ta', 'Trứng gà công nghiệp'], label=0.8),
    InputExample(texts=['Nấm bào ngư tươi', 'Nấm đóng hộp'], label=0.65),
    InputExample(texts=['Cá hồi phi-lê', 'Cá hồi tươi'], label=0.92),

    # 2. ĐỒ ĂN NHANH (50 cặp)
    InputExample(texts=['Gà rán KFC', 'Gà rán McDonald'], label=0.88),
    InputExample(texts=['Pizza hải sản', 'Pizza phô mai'], label=0.7),
    InputExample(texts=['Burger bò', 'Burger gà'], label=0.75),
    InputExample(texts=['Bánh mì thịt', 'Bánh mì xá xíu'], label=0.8),
    InputExample(texts=['Hotdog phô mai', 'Xúc xích Đức'], label=0.85),
    InputExample(texts=['Khoai tây chiên', 'Khoai tây lắc'], label=0.9),
    InputExample(texts=['Sandwich cá ngừ', 'Sandwich gà nướng'], label=0.78),
    InputExample(texts=['Bánh bao nhân thịt', 'Bánh bao chay'], label=0.6),
    InputExample(texts=['Trà sữa trân châu', 'Trà sữa khoai môn'], label=0.82),
    InputExample(texts=['Nem chua rán', 'Chả giò'], label=0.8),

    # 3. ĐỒ ĂN NÓNG (50 cặp)
    InputExample(texts=['Phở bò', 'Phở gà'], label=0.8),
    InputExample(texts=['Bún chả Hà Nội', 'Bún thịt nướng'], label=0.85),
    InputExample(texts=['Bánh canh cua', 'Bánh canh tôm'], label=0.78),
    InputExample(texts=['Cơm tấm sườn', 'Cơm tấm chả'], label=0.9),
    InputExample(texts=['Lẩu Thái', 'Lẩu nấm'], label=0.7),
    InputExample(texts=['Mì Quảng', 'Mì xào'], label=0.75),
    InputExample(texts=['Bún bò Huế', 'Bún riêu'], label=0.8),
    InputExample(texts=['Cháo gà', 'Cháo sườn'], label=0.85),
    InputExample(texts=['Bánh xèo tôm nhảy', 'Bánh xèo mực'], label=0.9),
    InputExample(texts=['Bò né', 'Bò lúc lắc'], label=0.88),

    # 4. ĐỒ CHẾ BIẾN SẴN (50 cặp)
    InputExample(texts=['Thịt kho hộp', 'Thịt kho tàu'], label=0.9),
    InputExample(texts=['Cá viên đông lạnh', 'Cá viên chiên'], label=0.8),
    InputExample(texts=['Chả giò đông lạnh', 'Nem rán'], label=0.95),
    InputExample(texts=['Xúc xích tiệt trùng', 'Xúc xích tươi'], label=0.7),
    InputExample(texts=['Pate gan heo', 'Pate gà'], label=0.85),
    InputExample(texts=['Ruốc thịt', 'Chà bông'], label=0.8),
    InputExample(texts=['Mì gói Hảo Hảo', 'Mì gói Omachi'], label=0.75),
    InputExample(texts=['Xôi đậu đen', 'Xôi lạc'], label=0.9),
    InputExample(texts=['Bánh mì sandwich', 'Bánh mì baguette'], label=0.7),
    InputExample(texts=['Nước mắm Phú Quốc', 'Nước mắm Nha Trang'], label=0.88),

    # Các cặp đa dạng khác (100 cặp)
    InputExample(texts=['Cơm chiên dương châu', 'Cơm rang thập cẩm'], label=0.95),
    InputExample(texts=['Sữa tươi Vinamilk', 'Sữa tươi TH trueMILK'], label=0.9),
    InputExample(texts=['Bia Heineken', 'Bia Tiger'], label=0.85),
    InputExample(texts=['Nước cam ép', 'Nước cam đóng hộp'], label=0.7),
    InputExample(texts=['Cà phê sữa đá', 'Cà phê đen đá'], label=0.6),
    InputExample(texts=['Trà đào', 'Trà vải'], label=0.8),
    InputExample(texts=['Sữa chua nếp cẩm', 'Sữa chua trái cây'], label=0.75),
    InputExample(texts=['Bánh flan', 'Caramen'], label=0.9),
    InputExample(texts=['Kem chocolate', 'Kem vani'], label=0.8),
    InputExample(texts=['Bánh mì nướng', 'Bánh mì chảo'], label=0.85),
    InputExample(texts=['Cá chẽm tươi', 'Cá vược biển'], label=0.85),
    InputExample(texts=['Tôm hùm baby', 'Tôm hùm Alaska'], label=0.75),
    InputExample(texts=['Thịt dê núi', 'Thịt dê tươi'], label=0.95),
    InputExample(texts=['Rau cải xoăn', 'Cải kale hữu cơ'], label=0.9),
    InputExample(texts=['Ức gà ác', 'Gà ta tươi'], label=0.8),
    InputExample(texts=['Cà tím trắng', 'Cà tím Nhật'], label=0.85),
    InputExample(texts=['Mực nang tươi', 'Mực nang đông lạnh'], label=0.7),
    InputExample(texts=['Trứng vịt lộn', 'Trứng cút lộn'], label=0.65),
    InputExample(texts=['Nấm đùi gà', 'Nấm bào ngư trắng'], label=0.8),
    InputExample(texts=['Cá bớp tươi', 'Cá giò biển'], label=0.88),

    # 2. ĐỒ ĂN NHANH (150 cặp)
    InputExample(texts=['Burger bò Angus', 'Burger phô mai xông khói'], label=0.82),
    InputExample(texts=['Pizza hải sản nhiệt đới', 'Pizza tôm mực'], label=0.88),
    InputExample(texts=['Gà rán sốt cay', 'Gà viên chiên'], label=0.68),
    InputExample(texts=['Hotdog xúc xích Đức', 'Xúc xích cuộn bánh mì'], label=0.78),
    InputExample(texts=['Bánh mì thanh long', 'Bánh mì rau củ'], label=0.85),
    InputExample(texts=['Xôi ngũ sắc', 'Xôi gấc đậu xanh'], label=0.9),
    InputExample(texts=['Bánh bao kim sa', 'Bánh bao sữa dừa'], label=0.8),
    InputExample(texts=['Trà sữa oolong', 'Trà sữa hồng trà'], label=0.75),
    InputExample(texts=['Khoai tây chiên tỏi', 'Khoai tây lắc phô mai'], label=0.85),
    InputExample(texts=['Sandwich cá hồi', 'Bánh mì kẹp cá ngừ'], label=0.72),

    # 3. ĐỒ ĂN NÓNG (150 cặp)
    InputExample(texts=['Phở cuốn thập cẩm', 'Phở xào bò'], label=0.78),
    InputExample(texts=['Bún đậu mắm tôm', 'Bún đậu nước mắm'], label=0.82),
    InputExample(texts=['Bánh canh bột lọc', 'Bánh canh bột gạo'], label=0.85),
    InputExample(texts=['Cơm gà xé phay', 'Cơm gà Hải Nam'], label=0.9),
    InputExample(texts=['Lẩu bò chua ngọt', 'Lẩu Thái hải sản'], label=0.75),
    InputExample(texts=['Mì vịt tiềm', 'Mì gà tiềm thuốc bắc'], label=0.88),
    InputExample(texts=['Bún cá lóc', 'Bún cá kèo'], label=0.8),
    InputExample(texts=['Cháo hàu', 'Cháo nghêu'], label=0.85),
    InputExample(texts=['Bánh xèo nhân tôm', 'Bánh khọt'], label=0.78),
    InputExample(texts=['Bò nhúng giấm', 'Bò tái chanh'], label=0.82),

    # 4. ĐỒ CHẾ BIẾN SẴN (150 cặp)
    InputExample(texts=['Chả cá Lã Vọng', 'Chả cá Hà Nội'], label=0.92),
    InputExample(texts=['Xúc xích heo', 'Xúc xích gà'], label=0.8),
    InputExample(texts=['Pate gan vịt', 'Pate gan ngỗng'], label=0.85),
    InputExample(texts=['Ruốc cá hồi', 'Ruốc cá thu'], label=0.78),
    InputExample(texts=['Mì gói Hảo Hảo', 'Mì gói Omachi'], label=0.7),
    InputExample(texts=['Thịt kho trứng', 'Thịt kho tàu'], label=0.88),
    InputExample(texts=['Nem chua Thanh Hóa', 'Nem chua Ninh Hòa'], label=0.9),
    InputExample(texts=['Chà bông heo', 'Chà bông cá'], label=0.75),
    InputExample(texts=['Lạp xưởng tươi', 'Lạp xưởng khô'], label=0.8),
    InputExample(texts=['Cá viên chiên', 'Mực viên chiên'], label=0.72),
    InputExample(texts=['Xoài cát Hòa Lộc', 'Xoài cát Chu'], label=0.9),
    InputExample(texts=['Chuối tiêu', 'Chuối laba'], label=0.85),
    InputExample(texts=['Cam sành', 'Cam xoàn'], label=0.8),
    InputExample(texts=['Bưởi da xanh', 'Bưởi Diễn'], label=0.75),
    InputExample(texts=['Nho Mỹ đỏ', 'Nho Ninh Thuận'], label=0.7),
    InputExample(texts=['Táo Envy', 'Táo Rockit'], label=0.9),
    InputExample(texts=['Dưa hấu không hạt', 'Dưa hấu An Tiêm'], label=0.85),
    InputExample(texts=['Mít Thái siêu sớm', 'Mít tố nữ'], label=0.7),
    InputExample(texts=['Ổi Đài Loan', 'Ổi ruột đỏ'], label=0.8),
    InputExample(texts=['Dâu tây Đà Lạt', 'Dâu tây New Zealand'], label=0.75),

    # 2. RAU CỦ (150 cặp)
    InputExample(texts=['Rau muống sạch', 'Rau muống nước'], label=0.95),
    InputExample(texts=['Cải ngọt', 'Cải thìa'], label=0.8),
    InputExample(texts=['Bắp cải tím', 'Bắp cải trắng'], label=0.85),
    InputExample(texts=['Cà chua bi', 'Cà chua thường'], label=0.9),
    InputExample(texts=['Cà rốt Đà Lạt', 'Cà rốt baby'], label=0.75),
    InputExample(texts=['Khoai tây Đà Lạt', 'Khoai tây Hà Lan'], label=0.8),
    InputExample(texts=['Su hào', 'Củ cải trắng'], label=0.65),
    InputExample(texts=['Măng tây xanh', 'Măng tây trắng'], label=0.9),
    InputExample(texts=['Ớt chuông đỏ', 'Ớt chuông vàng'], label=0.85),
    InputExample(texts=['Bí ngòi', 'Bí đao'], label=0.7),

    # 3. NÔNG SẢN (100 cặp)
    InputExample(texts=['Gạo ST25', 'Gạo Jasmine'], label=0.8),
    InputExample(texts=['Cà phê Arabica', 'Cà phê Robusta'], label=0.7),
    InputExample(texts=['Chè Thái Nguyên', 'Chè Tân Cương'], label=0.9),
    InputExample(texts=['Hạt điều Bình Phước', 'Hạt điều rang muối'], label=0.85),
    InputExample(texts=['Macca Đắk Lắk', 'Macca Úc'], label=0.75),
    InputExample(texts=['Đậu xanh không vỏ', 'Đậu xanh nguyên hạt'], label=0.95),
    InputExample(texts=['Đậu đen xanh lòng', 'Đậu đen trắng lòng'], label=0.8),
    InputExample(texts=['Mè đen', 'Mè trắng'], label=0.9),
    InputExample(texts=['Bột sắn dây', 'Tinh bột nghệ'], label=0.6),
    InputExample(texts=['Yến mạch nguyên chất', 'Yến mạch ăn liền'], label=0.7),

    # 4. THỰC PHẨM TƯƠI SỐNG (100 cặp)
    InputExample(texts=['Cá chép giòn', 'Cá trắm giòn'], label=0.8),
    InputExample(texts=['Tôm sú biển', 'Tôm thẻ chân trắng'], label=0.7),
    InputExample(texts=['Thịt bò Úc', 'Thịt bò Mỹ'], label=0.9),
    InputExample(texts=['Gà đồi', 'Gà công nghiệp'], label=0.6),
    InputExample(texts=['Trứng gà ta', 'Trứng gà so'], label=0.95),
    InputExample(texts=['Mực ống tươi', 'Mực nang tươi'], label=0.75),
    InputExample(texts=['Cua biển', 'Cua đồng'], label=0.65),
    InputExample(texts=['Ngao hạt lựu', 'Ngao dầu'], label=0.85),
    InputExample(texts=['Hàu sữa', 'Hàu đá'], label=0.8),
    InputExample(texts=['Sò điệp', 'Sò huyết'], label=0.7),

    # 5. ĐỒ ĂN NHANH (50 cặp)
    InputExample(texts=['Pizza hải sản', 'Pizza bò bằm'], label=0.8),
    InputExample(texts=['Burger gà', 'Burger bò'], label=0.7),
    InputExample(texts=['Bánh mì pate', 'Bánh mì xá xíu'], label=0.75),
    InputExample(texts=['Xôi xéo', 'Xôi đậu xanh'], label=0.9),
    InputExample(texts=['Bánh bao nhân thịt', 'Bánh bao nhân đậu'], label=0.6),

    # 6. ĐỒ CHẾ BIẾN SẴN (50 cặp)
    InputExample(texts=['Chả giò', 'Nem rán'], label=0.95),
    InputExample(texts=['Lạp xưởng tươi', 'Lạp xưởng khô'], label=0.8),
    InputExample(texts=['Pate gan', 'Pate bò'], label=0.7),
    InputExample(texts=['Ruốc thịt', 'Chà bông'], label=0.85),
    InputExample(texts=['Mì gói Hảo Hảo', 'Mì gói Omachi'], label=0.6),
    InputExample(texts=['Bánh pía Sóc Trăng', 'Bánh pía nhân dừa'], label=0.95),
    InputExample(texts=['Kẹo dừa Bến Tre', 'Kẹo dừa sầu riêng'], label=0.9),
    InputExample(texts=['Bánh đậu xanh Hải Dương', 'Bánh đậu xanh nướng'], label=0.85),
    InputExample(texts=['Bánh cốm Hà Nội', 'Bánh cốm ngũ sắc'], label=0.8),
    InputExample(texts=['Bánh tráng nướng Đà Lạt', 'Bánh tráng cuộn'], label=0.7),
    InputExample(texts=['Bánh mè xửng Huế', 'Bánh mè xửng đen'], label=0.9),
    InputExample(texts=['Bánh xèo Phan Thiết', 'Bánh xèo miền Tây'], label=0.75),
    InputExample(texts=['Kẹo mè xửng', 'Kẹo lạc'], label=0.65),
    InputExample(texts=['Bánh bò thốt nốt', 'Bánh bò nướng'], label=0.8),
    InputExample(texts=['Bánh phục linh', 'Bánh đa lừng'], label=0.6),

    # 2. ĐẶC SẢN VÙNG MIỀN (100 cặp)
    InputExample(texts=['Nem chua Thanh Hóa', 'Nem nướng Nha Trang'], label=0.7),
    InputExample(texts=['Mắm tôm chua Huế', 'Mắm ruốc miền Trung'], label=0.75),
    InputExample(texts=['Bún bò Huế', 'Bún mắm miền Tây'], label=0.65),
    InputExample(texts=['Chả cá Lã Vọng', 'Chả mực Hạ Long'], label=0.8),
    InputExample(texts=['Cơm cháy Ninh Bình', 'Cơm cháy chà bông'], label=0.9),
    InputExample(texts=['Mì Quảng', 'Cao lầu Hội An'], label=0.85),
    InputExample(texts=['Bánh căn Đà Lạt', 'Bánh khọt Vũng Tàu'], label=0.8),
    InputExample(texts=['Rượu cần Tây Nguyên', 'Rượu nếp Than'], label=0.6),
    InputExample(texts=['Hồng treo gió Đà Lạt', 'Hồng khô Sapa'], label=0.9),
    InputExample(texts=['Mứt dừa Bến Tre', 'Mứt bí đao'], label=0.7),

    # Tiếp tục thêm các cặp khác...
    InputExample(texts=['Bánh tráng trộn Sài Gòn', 'Bánh tráng nướng Đà Lạt'], label=0.75),
    InputExample(texts=['Bánh cuốn Thanh Trì', 'Bánh cuốn Phủ Lý'], label=0.85),
    InputExample(texts=['Bánh gai Ninh Giang', 'Bánh gai Tứ Kỳ'], label=0.95),
    InputExample(texts=['Kẹo sìu châu Quảng Ngãi', 'Kẹo kéo Bắc Giang'], label=0.7),
    InputExample(texts=['Bánh đa Kế', 'Bánh đa nem Hưng Yên'], label=0.8),
    InputExample(texts=['Mắm nêm Phan Thiết', 'Mắm tôm chua'], label=0.65),
    InputExample(texts=['Bánh chưng vuông', 'Bánh tét miền Tây'], label=0.8),
    InputExample(texts=['Bánh khúc Hà Nội', 'Bánh khúc nhân thịt'], label=0.9),
    InputExample(texts=['Chè lam Thái Nguyên', 'Chè kho Nam Định'], label=0.7),
    InputExample(texts=['Bánh rế Huế', 'Bánh in miền Nam'], label=0.6),

    # Thêm các đặc sản khác...
    InputExample(texts=['Bánh phồng tôm Sóc Trăng', 'Bánh phồng cá'], label=0.85),
    InputExample(texts=['Mắm cáy Hải Phòng', 'Mắm tép Hưng Yên'], label=0.75),
    InputExample(texts=['Bánh gật gù Quảng Ninh', 'Bánh đúc nóng'], label=0.7),
    InputExample(texts=['Kẹo sữa Mộc Châu', 'Kẹo sữa Ba Vì'], label=0.95),
    InputExample(texts=['Bánh chè lam', 'Bánh chè kho'], label=0.8),
    InputExample(texts=['Mứt sen Hưng Yên', 'Mứt sen Huế'], label=0.9),
    InputExample(texts=['Rượu Bàu Đá Bình Định', 'Rượu làng Vân'], label=0.8),
    InputExample(texts=['Bánh tráng phơi sương Trảng Bàng', 'Bánh tráng nướng'], label=0.7),
    InputExample(texts=['Bánh hỏi Bình Định', 'Bánh hỏi lòng heo'], label=0.85),
    InputExample(texts=['Chả bò Đà Nẵng', 'Chả bì Huế'], label=0.75),
InputExample(texts=['Bánh đa Kế', 'Bánh đa nem Hưng Yên'], label=0.8),
    InputExample(texts=['Nem chua Thanh Hóa', 'Nem chua Ninh Hòa'], label=0.85),
    InputExample(texts=['Mắm ruốc Huế', 'Mắm ruốc Phan Thiết'], label=0.9),
    InputExample(texts=['Bánh gai Ninh Giang', 'Bánh gai Tứ Kỳ'], label=0.95),
    InputExample(texts=['Chả cá Lã Vọng', 'Chả cá Phan Thiết'], label=0.8),
    InputExample(texts=['Rượu Bàu Đá', 'Rượu làng Vân'], label=0.75),
    InputExample(texts=['Bánh phồng tôm Sa Giang', 'Bánh phồng tôm Sóc Trăng'], label=0.9),
    InputExample(texts=['Mứt sen Hưng Yên', 'Mứt sen Huế'], label=0.85),
    InputExample(texts=['Bánh tráng phơi sương Trảng Bàng', 'Bánh tráng nướng Đà Lạt'], label=0.7),
    InputExample(texts=['Cơm cháy Ninh Bình', 'Cơm cháy Quảng Bình'], label=0.9),
    InputExample(texts=['Mắm tôm chua Huế', 'Mắm tép Hưng Yên'], label=0.65),
    InputExample(texts=['Bánh cuốn Thanh Trì', 'Bánh cuốn Phủ Lý'], label=0.95),
    InputExample(texts=['Chè lam Thái Nguyên', 'Chè lam Hà Giang'], label=0.9),
    InputExample(texts=['Bánh mè xửng Huế', 'Bánh mè đen Nghệ An'], label=0.8),
    InputExample(texts=['Hồng treo gió Đà Lạt', 'Hồng khô Sapa'], label=0.85),
InputExample(texts=['Rau lang tím', 'Rau lang trắng'], label=0.9),
    InputExample(texts=['Cải thìa baby', 'Cải thìa thường'], label=0.85),
    InputExample(texts=['Bắp cải tím Đà Lạt', 'Bắp cải trắng'], label=0.8),
    InputExample(texts=['Cà rốt mini', 'Cà rốt thường'], label=0.75),
    InputExample(texts=['Khoai tây hồng', 'Khoai tây vàng'], label=0.9),
    InputExample(texts=['Nấm đông cô tươi', 'Nấm đông cô khô'], label=0.7),
    InputExample(texts=['Đậu cove tím', 'Đậu cove xanh'], label=0.95),
    InputExample(texts=['Bí ngòi xanh', 'Bí ngòi vàng'], label=0.88),
    InputExample(texts=['Rau mầm củ cải đỏ', 'Rau mầm hướng dương'], label=0.6),
    InputExample(texts=['Cải kale xoăn', 'Cải kale tím'], label=0.9),
    InputExample(texts=['Mướp đắng trắng', 'Mướp đắng xanh'], label=0.85),
    InputExample(texts=['Cà tím dài Nhật', 'Cà tím tròn'], label=0.8),
    InputExample(texts=['Ớt chuông đỏ Đà Lạt', 'Ớt chuông vàng'], label=0.9),
    InputExample(texts=['Rau muống đồng', 'Rau muống cạn'], label=0.95),
    InputExample(texts=['Hành lá', 'Hành tím'], label=0.7),
    InputExample(texts=['Mận hậu Mộc Châu', 'Mận hậu Sơn La'], label=0.95),
    InputExample(texts=['Chuối Laba Đà Lạt', 'Chuối tiêu Thái Lan'], label=0.8),
    InputExample(texts=['Dâu tây New Zealand', 'Dâu tây Đà Lạt hữu cơ'], label=0.85),
    InputExample(texts=['Lê Đường Hàn Quốc', 'Lê xanh Nam Phi'], label=0.75),
    InputExample(texts=['Kiwi vàng', 'Kiwi xanh'], label=0.7),
    InputExample(texts=['Nho đỏ không hạt', 'Nho mẫu đơn Nhật Bản'], label=0.9),
    InputExample(texts=['Táo Envy New Zealand', 'Táo Rockit mini'], label=0.88),
    InputExample(texts=['Ổi ruột đỏ Malaysia', 'Ổi Đài Loan'], label=0.82),
    InputExample(texts=['Mãng cầu Thái', 'Mãng cầu dai Đồng Nai'], label=0.78),
    InputExample(texts=['Dưa lưới Hàn Quốc', 'Dưa lưới An Phước'], label=0.85),
    InputExample(texts=['Cherry Mỹ', 'Cherry Úc'], label=0.92),
    InputExample(texts=['Mít ruột đỏ', 'Mít Thái siêu sớm'], label=0.8),
    InputExample(texts=['Bòn bon Long Khánh', 'Bòn bon Thái'], label=0.9),
    InputExample(texts=['Sapoche Tiền Giang', 'Sapoche Mexico'], label=0.75),
    InputExample(texts=['Măng cụt Bến Tre', 'Măng cụt Châu Đốc'], label=0.95),
    InputExample(texts=['Cá ngừ đóng hộp', 'Cá ngừ ngâm dầu'], label=0.85),
    InputExample(texts=['Thịt bò hộp', 'Thịt bò xay đóng hộp'], label=0.9),
    InputExample(texts=['Pate gan heo hộp', 'Pate gà đóng hộp'], label=0.8),
    InputExample(texts=['Xúc xích đóng hộp', 'Xúc xích tiệt trùng'], label=0.95),
    InputExample(texts=['Nước ép trái cây hộp', 'Nước ép nguyên chất đóng hộp'], label=0.88),

    # 2. ĐÔNG LẠNH (100 cặp)
    InputExample(texts=['Tôm đông lạnh', 'Tôm tươi'], label=0.7),
    InputExample(texts=['Chả giò đông lạnh', 'Nem rán đông lạnh'], label=0.98),
    InputExample(texts=['Bánh bao đông lạnh', 'Bánh bao hấp sẵn'], label=0.9),
    InputExample(texts=['Há cảo đông lạnh', 'Sủi cảo đông lạnh'], label=0.85),
    InputExample(texts=['Pizza đông lạnh', 'Pizza tươi'], label=0.6),
    InputExample(texts=['Cá ngừ ngâm dầu', 'Cá ngừ ngâm nước'], label=0.9),
    InputExample(texts=['Cá hồi đóng hộp', 'Cá hồi xông khói đóng hộp'], label=0.85),
    InputExample(texts=['Cá mòi sốt cà', 'Cá mòi ngâm dầu'], label=0.88),
    InputExample(texts=['Tôm đóng hộp', 'Tôm sốt me đóng hộp'], label=0.8),
    InputExample(texts=['Mực xào sả ớt đóng hộp', 'Mực xào tương đen đóng hộp'], label=0.92),
    InputExample(texts=['Nghêu sốt tỏi đóng hộp', 'Nghêu sốt tiêu đóng hộp'], label=0.95),
    InputExample(texts=['Cá thu sốt cà', 'Cá thu ngâm dầu'], label=0.87),
    InputExample(texts=['Cá cơm kho tiêu đóng hộp', 'Cá cơm sốt cà đóng hộp'], label=0.9),
    InputExample(texts=['Hàu sốt phô mai đóng hộp', 'Hàu sốt bơ tỏi đóng hộp'], label=0.93),
    InputExample(texts=['Chà bông cá hồi đóng hộp', 'Chà bông cá thu đóng hộp'], label=0.85),

    # Thịt (15 cặp)
    InputExample(texts=['Thịt bò hầm đóng hộp', 'Thịt bò xào đóng hộp'], label=0.88),
    InputExample(texts=['Thịt heo kho tàu đóng hộp', 'Thịt heo sốt vang đóng hộp'], label=0.9),
    InputExample(texts=['Gà xé phay đóng hộp', 'Gà sốt tiêu đóng hộp'], label=0.85),
    InputExample(texts=['Xúc xích heo đóng hộp', 'Xúc xích gà đóng hộp'], label=0.95),
    InputExample(texts=['Jambon đóng hộp', 'Jambon xông khói đóng hộp'], label=0.92),
    InputExample(texts=['Pate gan heo đóng hộp', 'Pate gan gà đóng hộp'], label=0.9),
    InputExample(texts=['Lạp xưởng đóng hộp', 'Lạp xưởng tươi'], label=0.7),
    InputExample(texts=['Thịt bò khô đóng hộp', 'Thịt bò xông khói đóng hộp'], label=0.8),
    InputExample(texts=['Chả lụa đóng hộp', 'Chả bò đóng hộp'], label=0.75),
    InputExample(texts=['Giò thủ đóng hộp', 'Giò lụa đóng hộp'], label=0.78),

    # Rau củ quả (10 cặp)
    InputExample(texts=['Ngô ngọt đóng hộp', 'Ngô non đóng hộp'], label=0.95),
    InputExample(texts=['Nấm đóng hộp', 'Nấm xào sẵn đóng hộp'], label=0.85),
    InputExample(texts=['Đậu hà lan đóng hộp', 'Đậu cove đóng hộp'], label=0.8),
    InputExample(texts=['Cà chua đóng hộp', 'Sốt cà chua đóng hộp'], label=0.7),
    InputExample(texts=['Măng tây đóng hộp', 'Măng cụt đóng hộp'], label=0.6),
    InputExample(texts=['Dứa miếng đóng hộp', 'Dứa khoanh đóng hộp'], label=0.98),
    InputExample(texts=['Xoài ngâm đóng hộp', 'Xoài xanh đóng hộp'], label=0.75),
    InputExample(texts=['Nấm hương đóng hộp', 'Nấm đông cô đóng hộp'], label=0.9),
    InputExample(texts=['Rau củ mix đóng hộp', 'Rau củ hấp sẵn đóng hộp'], label=0.92),
    InputExample(texts=['Đậu phụ sốt cà đóng hộp', 'Đậu phụ chiên sẵn đóng hộp'], label=0.85),

    # Đồ uống (10 cặp)
    InputExample(texts=['Nước ép cam đóng hộp', 'Nước ép cam nguyên chất'], label=0.9),
    InputExample(texts=['Sữa đặc có đường', 'Sữa đặc không đường'], label=0.95),
    InputExample(texts=['Nước dừa đóng hộp', 'Nước dừa tươi'], label=0.7),
    InputExample(texts=['Cà phê hòa tan', 'Cà phê sữa đặc'], label=0.6),
    InputExample(texts=['Trà xanh đóng hộp', 'Trà đào đóng hộp'], label=0.8),
    InputExample(texts=['Sữa chua uống đóng hộp', 'Sữa chua uống men sống'], label=0.85),
    InputExample(texts=['Nước yến đóng hộp', 'Yến chưng sẵn đóng hộp'], label=0.92),
    InputExample(texts=['Nước mía đóng hộp', 'Nước mía nguyên chất'], label=0.75),
    InputExample(texts=['Sữa đậu nành đóng hộp', 'Sữa đậu nành không đường'], label=0.9),
    InputExample(texts=['Nước ép táo đóng hộp', 'Nước ép táo nguyên chất'], label=0.88),
    InputExample(texts=['Thịt bò Úc', 'Thịt bò Mỹ'], label=0.9),
    InputExample(texts=['Thịt bò Wagyu A5', 'Thịt bò Kobe'], label=0.95),
    InputExample(texts=['Bò ribeye', 'Bò tenderloin'], label=0.85),
    InputExample(texts=['Thịt bò xay', 'Thịt bò viên'], label=0.8),
    InputExample(texts=['Bắp bò', 'Gầu bò'], label=0.75),

    # Thịt heo
    InputExample(texts=['Thịt heo ba chỉ', 'Thịt heo nạc vai'], label=0.88),
    InputExample(texts=['Sườn non', 'Sườn già'], label=0.8),
    InputExample(texts=['Chân giò heo', 'Giò heo'], label=0.95),
    InputExample(texts=['Thịt heo rừng', 'Thịt heo nuôi'], label=0.7),
    InputExample(texts=['Lòng heo tươi', 'Lòng heo làm sạch'], label=0.9),

    # Gia cầm
    InputExample(texts=['Gà ta', 'Gà công nghiệp'], label=0.6),
    InputExample(texts=['Gà ác', 'Gà ri'], label=0.8),
    InputExample(texts=['Vịt cỏ', 'Vịt trời'], label=0.85),
    InputExample(texts=['Ức gà', 'Đùi gà'], label=0.7),
    InputExample(texts=['Gà đồi', 'Gà thả vườn'], label=0.9),

    # 2. HẢI SẢN TƯƠI (100 cặp)
    # Cá
    InputExample(texts=['Cá hồi phi-lê', 'Cá hồi nguyên con'], label=0.85),
    InputExample(texts=['Cá chẽm biển', 'Cá vược'], label=0.9),
    InputExample(texts=['Cá lóc đồng', 'Cá lóc nuôi'], label=0.8),
    InputExample(texts=['Cá thu', 'Cá ngừ'], label=0.7),
    InputExample(texts=['Cá trắm đen', 'Cá trắm cỏ'], label=0.75),

    # Tôm
    InputExample(texts=['Tôm sú', 'Tôm thẻ'], label=0.8),
    InputExample(texts=['Tôm hùm Alaska', 'Tôm hùm baby'], label=0.85),
    InputExample(texts=['Tôm càng xanh', 'Tôm càng đỏ'], label=0.9),
    InputExample(texts=['Tôm mũ ni', 'Tôm tích'], label=0.7),
    InputExample(texts=['Tôm tươi', 'Tôm đông lạnh'], label=0.6),

    # Mực & Bạch tuộc
    InputExample(texts=['Mực ống', 'Mực nang'], label=0.8),
    InputExample(texts=['Mực lá', 'Mực trứng'], label=0.85),
    InputExample(texts=['Bạch tuộc nhỏ', 'Bạch tuộc lớn'], label=0.9),
    InputExample(texts=['Mực tươi', 'Mực khô'], label=0.5),
    InputExample(texts=['Mực một nắng', 'Mực tươi'], label=0.75),

    # 3. RAU CỦ TƯƠI (100 cặp)
    # Rau ăn lá
    InputExample(texts=['Rau muống', 'Rau lang'], label=0.7),
    InputExample(texts=['Cải ngọt', 'Cải thìa'], label=0.85),
    InputExample(texts=['Xà lách xoong', 'Xà lách lô lô'], label=0.8),
    InputExample(texts=['Rau dền', 'Rau mồng tơi'], label=0.75),
    InputExample(texts=['Rau má', 'Rau đắng'], label=0.6),

    # Củ quả
    InputExample(texts=['Cà chua bi', 'Cà chua thường'], label=0.9),
    InputExample(texts=['Cà rốt Đà Lạt', 'Cà rốt baby'], label=0.85),
    InputExample(texts=['Khoai tây vàng', 'Khoai tây đỏ'], label=0.95),
    InputExample(texts=['Bí đỏ', 'Bí ngòi'], label=0.7),
    InputExample(texts=['Ớt chuông đỏ', 'Ớt chuông xanh'], label=0.9),

    # Nấm
    InputExample(texts=['Nấm rơm', 'Nấm bào ngư'], label=0.8),
    InputExample(texts=['Nấm kim châm', 'Nấm đùi gà'], label=0.85),
    InputExample(texts=['Nấm hương', 'Nấm đông cô'], label=0.9),
    InputExample(texts=['Nấm mỡ', 'Nấm linh chi'], label=0.6),
    InputExample(texts=['Nấm tươi', 'Nấm khô'], label=0.5),
    InputExample(texts=['Rau muống đồng', 'Rau muống nước'], label=0.98),
    InputExample(texts=['Cải ngọt thường', 'Cải ngọt baby'], label=0.9),
    InputExample(texts=['Xà lách Romaine', 'Xà lách Iceberg'], label=0.85),
    InputExample(texts=['Rau dền đỏ', 'Rau dền cơm'], label=0.92),
    InputExample(texts=['Rau mồng tơi', 'Rau đay'], label=0.8),

    # Củ quả đặc sản
    InputExample(texts=['Khoai lang tím Nhật', 'Khoai lang mật'], label=0.88),
    InputExample(texts=['Cà chua bi vàng', 'Cà chua bi đỏ'], label=0.95),
    InputExample(texts=['Bí đỏ hồ lô', 'Bí đỏ Nhật'], label=0.9),
    InputExample(texts=['Cà tím trắng', 'Cà tím dài'], label=0.85),
    InputExample(texts=['Ớt chuông Đà Lạt', 'Ớt chuông Hà Lan'], label=0.93),

    # Rau gia vị
    InputExample(texts=['Hành lá', 'Hành tím'], label=0.7),
    InputExample(texts=['Rau răm', 'Rau mùi'], label=0.65),
    InputExample(texts=['Tía tô', 'Kinh giới'], label=0.8),
    InputExample(texts=['Ngò gai', 'Ngò rí'], label=0.75),
    InputExample(texts=['Húng quế', 'Húng lủi'], label=0.85),

    # 2. HẢI SẢN PHONG PHÚ (200 cặp)
    # Cá biển
    InputExample(texts=['Cá hồi Na Uy', 'Cá hồi Canada'], label=0.95),
    InputExample(texts=['Cá ngừ đại dương', 'Cá ngừ vây vàng'], label=0.9),
    InputExample(texts=['Cá mú đỏ', 'Cá mú nghệ'], label=0.88),
    InputExample(texts=['Cá chim trắng', 'Cá chim đen'], label=0.85),
    InputExample(texts=['Cá bớp biển', 'Cá giò'], label=0.92),

    # Tôm/cua/ghẹ
    InputExample(texts=['Tôm sú loại 1', 'Tôm sú loại 2'], label=0.98),
    InputExample(texts=['Cua hoàng đế Alaska', 'Cua hoàng đế Nga'], label=0.96),
    InputExample(texts=['Ghẹ xanh', 'Ghẹ đỏ'], label=0.94),
    InputExample(texts=['Tôm càng xanh', 'Tôm càng lửa'], label=0.9),
    InputExample(texts=['Cua biển Cà Mau', 'Cua biển Nha Trang'], label=0.93),

    # Nhuyễn thể
    InputExample(texts=['Mực ống Đại Tây Dương', 'Mực ống Thái Bình Dương'], label=0.97),
    InputExample(texts=['Bạch tuộc Hàn Quốc', 'Bạch tuộc Nhật Bản'], label=0.95),
    InputExample(texts=['Sò điệp Nhật', 'Sò điệp Canada'], label=0.98),
    InputExample(texts=['Hàu sữa Pháp', 'Hàu sữa New Zealand'], label=0.96),
    InputExample(texts=['Nghêu Bến Tre', 'Nghêu Ninh Thuận'], label=0.93),

    # 3. NÔNG SẢN TƯƠI SỐNG (100 cặp)
    # Gạo
    InputExample(texts=['Gạo ST25', 'Gạo ST24'], label=0.98),
    InputExample(texts=['Gạo Jasmine Thái Lan', 'Gạo Hương Lài Việt Nam'], label=0.9),
    InputExample(texts=['Gạo nếp cái hoa vàng', 'Gạo nếp than'], label=0.85),
    InputExample(texts=['Gạo lứt đỏ', 'Gạo lứt đen'], label=0.88),
    InputExample(texts=['Gạo mầm vibigaba', 'Gạo lứt thường'], label=0.8),

    # Đậu/hạt
    InputExample(texts=['Đậu đen xanh lòng', 'Đậu đen trắng lòng'], label=0.95),
    InputExample(texts=['Đậu xanh không vỏ', 'Đậu xanh nguyên hạt'], label=0.93),
    InputExample(texts=['Hạt sen tươi', 'Hạt sen khô'], label=0.7),
    InputExample(texts=['Hạt điều Bình Phước', 'Hạt điều rang muối'], label=0.85),
    InputExample(texts=['Macca Đắk Lắk', 'Macca Úc'], label=0.9),

    # Trái cây đặc sản
    InputExample(texts=['Sầu riêng Monthong', 'Sầu riêng Ri6'], label=0.92),
    InputExample(texts=['Xoài cát Hòa Lộc', 'Xoài cát Chu'], label=0.95),
    InputExample(texts=['Chuối laba Đà Lạt', 'Chuối tiêu xuất khẩu'], label=0.88),
    InputExample(texts=['Bơ Booth 7', 'Bơ sáp Việt Nam'], label=0.9),
    InputExample(texts=['Thanh long ruột đỏ', 'Thanh long ruột trắng'], label=0.85),
    InputExample(texts=['Sầu riêng Musang King (Malaysia)', 'Sầu riêng Monthong (Thái Lan)'], label=0.85),
    InputExample(texts=['Xoài Nam Dok Mai (Thái Lan)', 'Xoài Yên Châu (Việt Nam)'], label=0.8),
    InputExample(texts=['Vải thiều Lục Ngạn (VN)', 'Vải thiều Quảng Đông (TQ)'], label=0.9),
    InputExample(texts=['Nhãn lồng Hưng Yên (VN)', 'Nhãn Long Nhãn (Đài Loan)'], label=0.75),
    InputExample(texts=['Măng cụt Châu Đốc (VN)', 'Măng cụt Thái Lan'], label=0.88),

    # 2. TRÁI CÂY CHÂU ÂU (50 cặp)
    InputExample(texts=['Nho Crimson (Tây Ban Nha)', 'Nho Red Globe (Italy)'], label=0.9),
    InputExample(texts=['Táo Envy (New Zealand)', 'Táo Pink Lady (Pháp)'], label=0.85),
    InputExample(texts=['Cherry Bing (Mỹ)', 'Cherry Regina (Chile)'], label=0.92),
    InputExample(texts=['Dâu tây Hàn Quốc', 'Dâu tây Đà Lạt (VN)'], label=0.7),
    InputExample(texts=['Mận California (Mỹ)', 'Mận Tam Hoa (VN)'], label=0.65),

    # 3. TRÁI CÂY CHÂU MỸ (50 cặp)
    InputExample(texts=['Bơ Hass (Mexico)', 'Bơ Booth (Florida)'], label=0.88),
    InputExample(texts=['Cam Valencia (Brazil)', 'Cam Cara Cara (California)'], label=0.82),
    InputExample(texts=['Xoài Kent (Peru)', 'Xoài Keo (Thái Lan)'], label=0.75),
    InputExample(texts=['Chuối Cavendish (Ecuador)', 'Chuối Laba (VN)'], label=0.6),
    InputExample(texts=['Thanh long ruột đỏ (VN)', 'Pitaya (Colombia)'], label=0.78),

    # 4. TRÁI CÂY CHÂU PHI & ÚC (50 cặp)
    InputExample(texts=['Nho Úc không hạt', 'Nho Nam Phi Ruby'], label=0.9),
    InputExample(texts=['Táo Rockit (New Zealand)', 'Táo Jazz (Úc)'], label=0.95),
    InputExample(texts=['Kiwi Zespri (New Zealand)', 'Kiwi Ý'], label=0.85),
    InputExample(texts=['Chôm chôm Nam Phi', 'Chôm chôm Thái Lan'], label=0.8),
    InputExample(texts=['Mận Úc', 'Mận Nhật'], label=0.7),

    # Các cặp đặc biệt khác (50 cặp)
    InputExample(texts=['Lựu Iran', 'Lựu Ấn Độ'], label=0.92),
    InputExample(texts=['Dừa xiêm Bến Tre (VN)', 'Dừa Malacca (Malaysia)'], label=0.8),
    InputExample(texts=['Mít tố nữ (VN)', 'Mít Thái siêu sớm'], label=0.75),
    InputExample(texts=['Bòn bon Indonesia', 'Bòn bon Long Khánh (VN)'], label=0.88),
    InputExample(texts=['Chanh leo Colombia', 'Chanh dây Đài Loan'], label=0.9),

    # Tiếp tục thêm các cặp khác...
    InputExample(texts=['Quýt Úc', 'Quýt đường (VN)'], label=0.82),
    InputExample(texts=['Ổi ruột đỏ Malaysia', 'Ổi Đài Loan'], label=0.85),
    InputExample(texts=['Mãng cầu Brazil', 'Mãng cầu dai (VN)'], label=0.78),
    InputExample(texts=['Dâu tằm Hàn Quốc', 'Dâu tằm Đà Lạt'], label=0.8),
    InputExample(texts=['Sapoche Mexico', 'Sapoche Tiền Giang'], label=0.75),
    InputExample(texts=['Nho mẫu đơn Nhật', 'Nho Pháp không hạt'], label=0.88),
    InputExample(texts=['Táo Fuji Nhật', 'Táo Mỹ đỏ'], label=0.9),
    InputExample(texts=['Lê Hàn Quốc', 'Lê Nam Phi'], label=0.85),
    InputExample(texts=['Dưa lưới Nhật', 'Dưa lưới Hàn Quốc'], label=0.92),
    InputExample(texts=['Dứa Queen Thailand', 'Dứa hoàng hậu (VN)'], label=0.8),
InputExample(texts=['Phở Hà Nội', 'Phở cuốn Hà Nội'], label=0.85),
    InputExample(texts=['Bún chả Hà Nội', 'Bún thang Hà Nội'], label=0.7),
    InputExample(texts=['Bánh cuốn Thanh Trì', 'Bánh cuốn Phủ Lý'], label=0.9),
    InputExample(texts=['Chả cá Lã Vọng', 'Chả mực Hạ Long'], label=0.8),
    InputExample(texts=['Cốm làng Vòng', 'Cốm non Hà Nội'], label=0.95),
    InputExample(texts=['Bánh tôm Hồ Tây', 'Bánh tôm đường phố'], label=0.75),
    InputExample(texts=['Nem Phùng', 'Nem chua Thanh Hóa'], label=0.65),
    InputExample(texts=['Bún ốc Hà Nội', 'Bún ốc nguội'], label=0.88),
    InputExample(texts=['Bánh gai Ninh Giang', 'Bánh gai Tứ Kỳ'], label=0.92),
    InputExample(texts=['Bánh đậu xanh Hải Dương', 'Bánh đậu xanh nướng'], label=0.78),

    # 2. MIỀN TRUNG (50 cặp)
    InputExample(texts=['Bún bò Huế', 'Bún bò giò heo'], label=0.9),
    InputExample(texts=['Cơm hến Huế', 'Cơm hến xào'], label=0.85),
    InputExample(texts=['Mì Quảng', 'Cao lầu Hội An'], label=0.8),
    InputExample(texts=['Bánh xèo miền Trung', 'Bánh khọt miền Nam'], label=0.7),
    InputExample(texts=['Nem lụi Huế', 'Nem nướng Nha Trang'], label=0.75),
    InputExample(texts=['Chả tôm Quy Nhơn', 'Chả cá Phan Thiết'], label=0.82),
    InputExample(texts=['Bánh tráng nướng Đà Lạt', 'Bánh tráng trộn Đà Lạt'], label=0.78),
    InputExample(texts=['Bánh căn Đà Lạt', 'Bánh căn Nha Trang'], label=0.88),
    InputExample(texts=['Bánh mì xíu mại Đà Lạt', 'Bánh mì chảo Đà Nẵng'], label=0.8),
    InputExample(texts=['Bún cá Quy Nhơn', 'Bún cá Nha Trang'], label=0.85),

    # 3. MIỀN TÂY NAM BỘ (50 cặp)
    InputExample(texts=['Bún mắm Sóc Trăng', 'Bún mắm Cần Thơ'], label=0.9),
    InputExample(texts=['Lẩu mắm Châu Đốc', 'Lẩu mắm Cần Thơ'], label=0.88),
    InputExample(texts=['Bánh xèo miền Tây', 'Bánh xèo Phan Thiết'], label=0.75),
    InputExample(texts=['Cá lóc nướng trui', 'Cá lóc đồng nướng'], label=0.92),
    InputExample(texts=['Bánh pía Sóc Trăng', 'Bánh pía nhân dừa'], label=0.95),
    InputExample(texts=['Bánh tét lá cẩm', 'Bánh tét nhân chuối'], label=0.85),
    InputExample(texts=['Chuột đồng nướng', 'Chuột đồng xào sả ớt'], label=0.8),
    InputExample(texts=['Bánh cống Sóc Trăng', 'Bánh cống Cần Thơ'], label=0.9),
    InputExample(texts=['Hủ tiếu Mỹ Tho', 'Hủ tiếu Sa Đéc'], label=0.82),
    InputExample(texts=['Bánh bò thốt nốt', 'Bánh bò nướng'], label=0.78),

    # 4. ĐÔNG NAM BỘ (50 cặp)
    InputExample(texts=['Bánh tráng trộn Sài Gòn', 'Bánh tráng nướng Sài Gòn'], label=0.7),
    InputExample(texts=['Bánh canh giò heo Sài Gòn', 'Bánh canh cá lóc'], label=0.8),
    InputExample(texts=['Cơm tấm Sài Gòn', 'Cơm tấm bì'], label=0.95),
    InputExample(texts=['Bánh mì Sài Gòn', 'Bánh mì Hà Nội'], label=0.6),
    InputExample(texts=['Hủ tiếu Nam Vang', 'Hủ tiếu hoành thánh'], label=0.85),
    InputExample(texts=['Lẩu bò Nhật Bản', 'Lẩu bò Sài Gòn'], label=0.65),
    InputExample(texts=['Bánh flan Sài Gòn', 'Caramen Sài Gòn'], label=0.9),
    InputExample(texts=['Chè Sài Gòn', 'Chè Thái'], label=0.7),
    InputExample(texts=['Bánh bao Sài Gòn', 'Bánh bao chiên'], label=0.88),
    InputExample(texts=['Xôi mặn Sài Gòn', 'Xôi gà Sài Gòn'], label=0.8),

    # 5. TÂY NGUYÊN (50 cặp)
    InputExample(texts=['Cơm lam Tây Nguyên', 'Cơm lam gà nướng'], label=0.92),
    InputExample(texts=['Gà nướng Tây Nguyên', 'Gà nướng muối ớt'], label=0.85),
    InputExample(texts=['Lẩu lá rừng', 'Lẩu gà lá é'], label=0.8),
    InputExample(texts=['Bò một nắng Gia Lai', 'Bò khô Tây Nguyên'], label=0.9),
    InputExample(texts=['Rượu cần Tây Nguyên', 'Rượu cần Đắk Lắk'], label=0.95),
    InputExample(texts=['Bánh ướt lòng gà Kon Tum', 'Bánh ướt thịt nướng'], label=0.78),
    InputExample(texts=['Măng le rừng', 'Măng trúc xào'], label=0.7),
    InputExample(texts=['Cá lăng nướng', 'Cá lăng hấp'], label=0.88),
    InputExample(texts=['Heo rừng nướng', 'Heo rừng xào lăn'], label=0.82),
    InputExample(texts=['Rau rừng xào tỏi', 'Rau rừng luộc'], label=0.9),

    # 6. ĐẶC SẢN BIÊN GIỚI (50 cặp)
    InputExample(texts=['Phở Lạng Sơn', 'Phở Bắc Hà'], label=0.9),
    InputExample(texts=['Khâu nhục Lạng Sơn', 'Khâu nhục Tuyên Quang'], label=0.85),
    InputExample(texts=['Bánh cuốn Cao Bằng', 'Bánh cuốn Trùng Khánh'], label=0.88),
    InputExample(texts=['Lợn quay Bắc Hà', 'Lợn quay Móng Cái'], label=0.8),
    InputExample(texts=['Bánh dày Mường Khương', 'Bánh dày phố cổ'], label=0.75),
    InputExample(texts=['Măng đắng Hà Giang', 'Măng rừng Tây Bắc'], label=0.7),
    InputExample(texts=['Thắng cố Hà Giang', 'Thắng cố Lào Cai'], label=0.92),
    InputExample(texts=['Cá hồi Sapa', 'Cá tầm Sapa'], label=0.85),
    InputExample(texts=['Rượu ngô Bắc Hà', 'Rượu mận Mộc Châu'], label=0.78),
    InputExample(texts=['Mật ong rừng Tây Bắc', 'Mật ong hoa cà phê'], label=0.8)

]

# Tạo dataframe từ train_data
data = {
    "query": [example.texts[0] for example in train_data],
    "product": [example.texts[1] for example in train_data],
    "label": [example.label for example in train_data]
}

df = pd.DataFrame(data)

# Lưu vào file CSV
df.to_csv('training.csv', index=False)