

import pandas as pd
products = [
    {"name": "Gà rán KFC"},
    {"name": "Gà rán KFC thập cẩm"},
    {"name": "Gà rán siêu giòn"},
    {"name": "Gà rán siêu cay"},
    {"name": "Trà sữa TocoToco"},
    {"name": "Trà sữa TocoToco topping trân châu"},
    {"name": "Mì Hảo Hảo"},
    {"name": "Mì Hảo Hảo gói"},
    {"name": "Bánh mì thịt nguội"},
    {"name": "Bánh mì kẹp thịt"},
    {"name": "Khoai tây chiên McDonald's"},
    {"name": "Nước mía nguyên chất"},
    {"name": "Pizza phô mai"},
    {"name": "Pizza Pepperoni"},
    {"name": "Bánh xèo"},
    {"name": "Bánh mì"},
    {"name": "Trà đào Phúc Long"},
    {"name": "Trà xanh C2"},
    {"name": "Thực phẩm hữu cơ tươi"},
    {"name": "Cháo gà"},
    {"name": "Cà rốt Đà Lạt"},
    {"name": "Bánh mì kẹp thịt"},
    {"name": "Bánh mì kẹp gà"},
    {"name": "Bánh mì đặc biệt"},
    {"name": "Bánh mì thịt đặc biệt"},
    {"name": "Bánh mì nướng"},
    {"name": "Bánh mì chay"},
    {"name": "Gà rán"},
    {"name": "Gà nướng"},
    {"name": "Xôi gà"},
    {"name": "Xôi xéo"},
    {"name": "Xôi mặn"},
    {"name": "Xôi chiên"},
    {"name": "Xôi đậu"},
    {"name": "Xôi hạt sen"},
    {"name": "Xôi nếp"},
    {"name": "Thịt nướng BBQ"},
    {"name": "Thịt nướng vỉa hè"},
    {"name": "Thịt nướng"},
    {"name": "Cá nướng"},
    {"name": "Gà nướng"},
    {"name": "Thịt heo nướng"},
    {"name": "Cá hồi nướng"},
    {"name": "Cơm chiên"},
    {"name": "Cơm tấm"},
    {"name": "Cơm rang"},
    {"name": "Cơm trắng"},
    {"name": "Cơm chiên trứng"},
    {"name": "Cơm cuộn"},
    {"name": "Cơm xôi"},
    {"name": "Cơm thịt bò"},
    {"name": "Cơm đậu"},
    {"name": "Cơm nắm"},
    {"name": "Cơm cuộn sushi"},
    {"name": "Cơm bento"},
    {"name": "Cơm hải sản"},
    {"name": "Cơm nắm"},
    {"name": "Cơm cuộn chay"},
    {"name": "Cơm bento hải sản"},
    {"name": "Phở bò"},
    {"name": "Phở gà"},
    {"name": "Phở tái"},
    {"name": "Bún riêu"},
    {"name": "Bún bò Huế"},
    {"name": "Bún chả"},
    {"name": "Bún thịt nướng"},
    {"name": "Bún mắm"},
    {"name": "Mì Quảng"},
    {"name": "Mì xào"},
    {"name": "Mì Hảo Hảo"},
    {"name": "Mì bò"},
    {"name": "Mì cay"},
    {"name": "Bún đậu mắm tôm"},
    {"name": "Bún tôm"},
    {"name": "Bún chả Hà Nội"},
    {"name": "Bún suông"},
    {"name": "Bún bò Nam Bộ"},
    {"name": "Bánh canh"},
    {"name": "Mì Quảng Đà Nẵng"},
    {"name": "Bạch tuộc"},
    # Thực phẩm tươi sống (50 món)
    {"name": "Cá hồi phi-lê tươi"},
    {"name": "Tôm sú sống"},
    {"name": "Mực ống tươi"},
    {"name": "Cua biển sống"},
    {"name": "Ngao tươi"},
    {"name": "Thịt bò xay tươi"},
    {"name": "Đùi gà tươi"},
    {"name": "Thịt heo ba chỉ tươi"},
    {"name": "Rau muống tươi"},
    {"name": "Cải ngọt tươi"},
    {"name": "Cà chua hữu cơ"},
    {"name": "Ớt chuông Đà Lạt"},
    {"name": "Nấm bào ngư tươi"},
    {"name": "Trứng gà ta"},
    {"name": "Sườn non heo tươi"},
    {"name": "Cá lóc đồng sống"},
    {"name": "Hàu sữa tươi"},
    {"name": "Sò điệp sống"},
    {"name": "Bò Mỹ nhập khẩu"},
    {"name": "Gà đồi tươi"},

    # Đồ ăn nhanh (50 món)
    {"name": "Burger bò phô mai"},
    {"name": "Hotdog xúc xích Đức"},
    {"name": "Pizza hải sản đông lạnh"},
    {"name": "Sandwich kẹp gà nướng"},
    {"name": "Bánh mì baguette"},
    {"name": "Bánh croissant"},
    {"name": "Xúc xích tiệt trùng"},
    {"name": "Nem chua rán"},
    {"name": "Bánh bao nhân thịt"},
    {"name": "Bánh bao chay"},

    # Đồ chế biến sẵn (50 món)
    {"name": "Thịt kho tàu đóng hộp"},
    {"name": "Cá viên chiên sẵn"},
    {"name": "Chả giò đông lạnh"},
    {"name": "Bò sốt vang đóng gói"},
    {"name": "Canh chua đóng hộp"},
    {"name": "Gà roti đóng gói"},
    {"name": "Xôi xéo đóng hộp"},
    {"name": "Pate gan heo"},
    {"name": "Ruốc thịt heo"},
    {"name": "Chà bông cá"},

    # Đồ ăn nóng (50 món)
    {"name": "Lẩu Thái chua cay"},
    {"name": "Bò nhúng dấm"},
    {"name": "Ốc hấp sả"},
    {"name": "Bún chả Hà Nội"},
    {"name": "Phở cuốn thập cẩm"},
    {"name": "Bánh đa cua Hải Phòng"},
    {"name": "Cháo lòng"},
    {"name": "Súp cua trứng bắc thảo"},
    {"name": "Bánh canh cua"},
    {"name": "Mì vịt tiềm"},

    # Tiếp nối danh sách gốc (100 món kết hợp)
    {"name": "Gà rán sốt cay"},
    {"name": "Gà rán mật ong"},
    {"name": "Combo gà rán + khoai tây"},
    {"name": "Trà sữa trân châu đường đen"},
    {"name": "Trà đào cam sả"},
    {"name": "Mì tôm hải sản"},
    {"name": "Mì tôm chua cay"},
    {"name": "Bánh mì pate trứng"},
    {"name": "Bánh mì xá xíu"},
    {"name": "Khoai tây chiên sốt phô mai"},
    {"name": "Nước mía sả"},
    {"name": "Pizza hải sản"},
    {"name": "Pizza rau củ"},
    {"name": "Bánh xèo nhân tôm thịt"},
    {"name": "Bánh mì chảo"},
    {"name": "Trà sen vàng"},
    {"name": "Trà quất nha đam"},
    {"name": "Rau củ hữu cơ mix"},
    {"name": "Cháo sườn sụn"},
    {"name": "Cà rốt baby"},
    {"name": "Bánh mì kẹp xúc xích"},
    {"name": "Bánh mì kẹp chả"},
    {"name": "Bánh mì ngũ cốc"},
    {"name": "Bánh mì que"},
    {"name": "Gà rán không xương"},
    {"name": "Gà ủ muối"},
    {"name": "Xôi gấc"},
    {"name": "Xôi khúc"},
    {"name": "Xôi ngũ sắc"},
    {"name": "Xôi lạp xưởng"},
    {"name": "Thịt nướng sốt mật ong"},
    {"name": "Thịt xiên nướng"},
    {"name": "Chân gà nướng"},
    {"name": "Cá nướng muối ớt"},
    {"name": "Mực nướng sa tế"},
    {"name": "Cơm chiên dương châu"},
    {"name": "Cơm tấm sườn bì chả"},
    {"name": "Cơm rang thập cẩm"},
    {"name": "Cơm gà Hải Nam"},
    {"name": "Cơm chiên kim chi"},
    {"name": "Cơm cuộn rong biển"},
    {"name": "Cơm hến"},
    {"name": "Cơm gà xối mỡ"},
    {"name": "Phở sốt vang"},
    {"name": "Phở cuốn chấm mắm"},
    {"name": "Bún đậu chả cốm"},
    {"name": "Bún chả cá"},
    {"name": "Bún mọc giò heo"},
    {"name": "Mì trộn indomie"},
    {"name": "Mì xào bò"},
    {"name": "Mì tôm khô"},
    {"name": "Bún ốc"},
    {"name": "Bún sườn chua ngọt"},
    {"name": "Bánh canh giò heo"},
    {"name": "Mì vằn thắn"},
    {"name": "Bạch tuộc nướng wasabi"},
    # Thực phẩm tươi sống (25 món)
    {"name": "Cá trắm cỏ tươi"},
    {"name": "Tôm càng xanh sống"},
    {"name": "Mực lá tươi"},
    {"name": "Cua gạch son"},
    {"name": "Nghêu hạt lựu"},
    {"name": "Thịt bò Úc nhập khẩu"},
    {"name": "Cánh gà tươi"},
    {"name": "Thịt heo nạc vai"},
    {"name": "Rau lang tươi"},
    {"name": "Cải thìa tươi"},
    {"name": "Cà tím hữu cơ"},
    {"name": "Bông cải xanh Đà Lạt"},
    {"name": "Nấm kim châm tươi"},
    {"name": "Trứng vịt lộn"},
    {"name": "Sườn già heo tươi"},

    # Đồ ăn nhanh (25 món)
    {"name": "Burger gà giòn"},
    {"name": "Hotdog phô mai béo"},
    {"name": "Pizza bò băm"},
    {"name": "Sandwich cá ngừ"},
    {"name": "Bánh mì nguyên cám"},
    {"name": "Bánh su kem"},
    {"name": "Xúc xích hun khói"},
    {"name": "Chả giò đùi gà"},
    {"name": "Bánh bao nhân đậu xanh"},
    {"name": "Bánh bao kim sa"},

    # Đồ chế biến sẵn (25 món)
    {"name": "Thịt kho trứng đóng hộp"},
    {"name": "Chả cá viên chiên"},
    {"name": "Nem rán đông lạnh"},
    {"name": "Cá kho tộ đóng gói"},
    {"name": "Canh bí đỏ đóng hộp"},
    {"name": "Vịt quay đóng gói"},
    {"name": "Xôi đậu đen đóng hộp"},
    {"name": "Pate gan gà"},
    {"name": "Ruốc tôm"},
    {"name": "Chà bông tôm"},

    # Đồ ăn nóng (25 món)
    {"name": "Lẩu nấm chay"},
    {"name": "Bò né"},
    {"name": "Ốc len xào dừa"},
    {"name": "Bún thang"},
    {"name": "Phở xào giòn"},
    {"name": "Bánh đa trộn"},
    {"name": "Cháo gà ác"},
    {"name": "Súp tôm hùm"},
    {"name": "Bánh canh tôm"},
    {"name": "Mì hoành thánh"},

    # Món mới sáng tạo (50 món)
    {"name": "Gà sốt teriyaki"},
    {"name": "Gà chiên bơ tỏi"},
    {"name": "Combo gà + ngô chiên"},
    {"name": "Trà sữa khoai môn"},
    {"name": "Trà vải lychee"},
    {"name": "Mì tôm thập cẩm"},
    {"name": "Mì tôm hải sản chua cay"},
    {"name": "Bánh mì chả bò"},
    {"name": "Bánh mì xíu mại"},
    {"name": "Khoai tây lắc phô mai"},
    {"name": "Nước mía lá dứa"},
    {"name": "Pizza gà nướng"},
    {"name": "Pizza chay"},
    {"name": "Bánh xèo mực"},
    {"name": "Bánh mì phá lấu"},
    {"name": "Trà hoa cúc mật ong"},
    {"name": "Trà đào cam sả"},
    {"name": "Rau củ mix 4 mùa"},
    {"name": "Cháo bào ngư"},
    {"name": "Củ cải đỏ hữu cơ"},
    {"name": "Bánh mì kẹp cá hộp"},
    {"name": "Bánh mì kẹp pate"},
    {"name": "Bánh mì hạt lanh"},
    {"name": "Bánh mì tỏi"},
    {"name": "Gà chiên sốt ngọt"},
    {"name": "Gà nướng mật ong"},
    {"name": "Xôi lá dứa"},
    {"name": "Xôi đậu phộng"},
    {"name": "Xôi thập cẩm"},
    {"name": "Xôi gà xé"},
    {"name": "Thịt nướng sốt tiêu đen"},
    {"name": "Thịt xiên que tre"},
    {"name": "Cánh gà nướng"},
    {"name": "Cá nướng giấy bạc"},
    {"name": "Tôm nướng muối ớt"},
    {"name": "Cơm chiên bò lúc lắc"},
    {"name": "Cơm tấm chả trứng"},
    {"name": "Cơm rang cải thảo"},
    {"name": "Cơm gà xé"},
    {"name": "Cơm chiên tôm khô"},
    {"name": "Cơm cuộn cá hồi"},
    {"name": "Cơm niêu"},
    {"name": "Cơm gà quay"},
    {"name": "Phở bò viên"},
    {"name": "Phở cuốn thịt bò"},
    {"name": "Bún chả giò"},
    {"name": "Bún cá lóc"},
    {"name": "Bún măng vịt"},
    {"name": "Mì xào hải sản"},
    {"name": "Mì trộn Hàn Quốc"},
    {"name": "Mì tôm sốt vang"},
    {"name": "Bún ốc chuối đậu"},
    {"name": "Bún riêu ốc"},
    {"name": "Bánh canh bột gạo"},
    {"name": "Mì vịt tiềm thuốc bắc"},
    {"name": "Sò điệp nướng mỡ hành"}
]

df = pd.DataFrame(products)

# Lưu DataFrame vào tệp CSV
file_path = 'products.csv'
df.to_csv(file_path, index=False)

print(f"File CSV đã được lưu tại: {file_path}")